#!/usr/bin/env python3
# pylint: disable=missing-function-docstring

import argparse
from pathlib import Path
import sys

from moca_cfg import MoCAFiles

def main():
    parser = argparse.ArgumentParser(
        description='Manipulate the filesystem on a BCM6802-based MoCA adapter.'
    )
    parser.add_argument(
        '-H', '--host',
        type=str, nargs=1,
        default='192.168.144.30'
    )
    parser.add_argument('--outfile', '-o', type=Path, nargs=1, default=None)
    parser.add_argument('file', type=str, nargs='*')
    args = parser.parse_args()

    output = args.outfile
    if output is None:
        output = sys.stdout
        progress = None
    else:
        output = open(output[0], 'w+')
        progress = sys.stdout

    m = MoCAFiles(args.host[0])
    if len(args.file) == 0:
        files = m.get_file_map()
        for name in files:
            print(name, file=output)

    for f in args.file:
        m.get_file(f, output.buffer, progress)

    return 0

if __name__ == "__main__":
    sys.exit(main())
